baseurl = "https://example.com/"
title = "Whiteplain"
# themesDir = "../../"
theme = "whiteplain"
languageCode = "ja"
# Disqus shortname
#disqusShortname = ""
# google analytics tracking id
#googleAnalytics = ""
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2017 Foo Bar"



